### ISSUE TITLE
Switching from travis to git-workflows.

### ISSUE THREAD

**Issue by frobnitzem** [bssw-tutorial/hello-numerical-world#9]
@jwillenbring has proposed circle-ci, @markcmiller86 has proposed github-actions.  In either case, we need to replace travis.  I'll test out the actions method.

**Comment by markcmiller86** [comment]
If you wanna keep things simple, I strongly encourage GitHub actions for hands-on. People don't need to have accounts elsewhere.

**Comment by jwillenbring** [comment]
I am also OK with GitHub Actions. Circle-CI was a possibility that came out of some investigation I did into the issue, but I did not use it enough to endorse it. GitHub Actions only applies to GitHub (not BitBucket or GitLab), but I think it is a very reasonable choice in this context.

**Comment by bernhold** [comment]
@frobnitzem are we done with this now?  If so, feel free to close.  Otherwise, what else do we need to do?
